backen deploy

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -330,67 +330,67 @@ jobs:
       - revert-migrations
       # Here's where you will add some code to rollback on failure
 
-  smoke-test:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
-      - install_awscli
-      - install_nodejs
-      - run:
-          name: Backend Smoke test.
-          command: |
-            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --output text)
-            API_URL="http://${BACKEND_PUBLIC_IP}:3030/api/status"
-            echo "${API_URL}"
-            if curl -s "${API_URL}" | grep "ok"
-            then
-                exit 0
-            else
-                exit 1
-            fi
-  - run:
-      name: Frontend Smoke test.
-      command: |
-        URL="https://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3.amazonaws.com/index.html#/employees"
-        echo ${URL}
-        if curl -s ${URL} | grep "Welcome"
-        then
-          exit 0
-        else
-          exit 1
-        fi
-  - destroy-environment
-  - revert-migrations
-  # Here's where you will add some code to rollback on failure
+  # smoke-test:
+  #   docker:
+  #     - image: cimg/base:stable
+  #   steps:
+  #     - checkout
+  #     - install_awscli
+  #     - install_nodejs
+  #     - run:
+  #         name: Backend Smoke test.
+  #         command: |
+  #           BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+  #             --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+  #             --query 'Reservations[*].Instances[*].PublicIpAddress' \
+  #             --output text)
+  #           API_URL="http://${BACKEND_PUBLIC_IP}:3030/api/status"
+  #           echo "${API_URL}"
+  #           if curl -s "${API_URL}" | grep "ok"
+  #           then
+  #               exit 0
+  #           else
+  #               exit 1
+  #           fi
+  # - run:
+  #     name: Frontend Smoke test.
+  #     command: |
+  #       URL="https://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3.amazonaws.com/index.html#/employees"
+  #       echo ${URL}
+  #       if curl -s ${URL} | grep "Welcome"
+  #       then
+  #         exit 0
+  #       else
+  #         exit 1
+  #       fi
+  # - destroy-environment
+  # - revert-migrations
+  # # Here's where you will add some code to rollback on failure
 
-  cloudfront-update:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
-      - install_awscli
-      - install_nodejs
-      - run:
-          name: Store Old WorkFlow ID.
-          command: |
-            export OldWorkflowID=$(aws cloudformation \
-                      list-exports --query "Exports[?Name==\`UdapeopleWorkflowID\`].Value" \
-                      --no-paginate --output text)
-            echo "Old WorkFlow ID : ${OldWorkflowID}"
-            curl https://kvdb.io/${KVDB_BUCKET}/OldWorkflowID -d "${OldWorkflowID}"
-      - run:
-          name: Update cloudfront Distribution
-          command: |
-            aws cloudformation deploy \
-              --template-file .circleci/files/cloudfront.yml \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" \
-              --stack-name initialstack
-      - destroy-environment
-      - revert-migrations
+  # cloudfront-update:
+  #   docker:
+  #     - image: cimg/base:stable
+  #   steps:
+  #     - checkout
+  #     - install_awscli
+  #     - install_nodejs
+  #     - run:
+  #         name: Store Old WorkFlow ID.
+  #         command: |
+  #           export OldWorkflowID=$(aws cloudformation \
+  #                     list-exports --query "Exports[?Name==\`UdapeopleWorkflowID\`].Value" \
+  #                     --no-paginate --output text)
+  #           echo "Old WorkFlow ID : ${OldWorkflowID}"
+  #           curl https://kvdb.io/${KVDB_BUCKET}/OldWorkflowID -d "${OldWorkflowID}"
+  #     - run:
+  #         name: Update cloudfront Distribution
+  #         command: |
+  #           aws cloudformation deploy \
+  #             --template-file .circleci/files/cloudfront.yml \
+  #             --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" \
+  #             --stack-name initialstack
+  #     - destroy-environment
+  #     - revert-migrations
       # Here's where you will add some code to rollback on failure
 
   # cleanup:
@@ -458,8 +458,8 @@ workflows:
           requires: [run-migrations]
       - deploy-backend:
           requires: [run-migrations]
-      - smoke-test:
-          requires: [deploy-backend, deploy-frontend]
+      # - smoke-test:
+      #     requires: [deploy-backend, deploy-frontend]
       # - cloudfront-update:
       #     requires: [smoke-test]
       # - cleanup:
